name: nasa_challenge
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  cached_network_image: ^3.3.1
  dio: ^5.5.0+1
  dio_logger_request: ^1.0.3
  flutter_dotenv: ^5.1.0
  flutter_mobx: ^2.2.1+1
  flutter_modular: ^6.3.4
  hive: ^2.2.3
  intl: ^0.19.0
  mobx: ^2.3.3+2
  photo_view: ^0.15.0
  salomon_bottom_bar: ^3.3.2
  video_player: ^2.9.2

dev_dependencies:
  build_runner: ^2.4.9
  mobx_codegen: ^2.6.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/images/
